### ISSUE TITLE
RESOURCE_ACCESS_DENIED

### ISSUE THREAD

**Issue by shauge78** [yenoiwesa/homebridge-connexoon#61]
I get this error code:

[6/23/2022, 7:57:53 AM] [Connexoon] Failed to get device list {
  errorCode: 'RESOURCE_ACCESS_DENIED',
  error: 'Too many attempts with an invalid token, temporarily banned.'
}
[6/23/2022, 7:57:53 AM] [Connexoon] Could not initialise platform, will retry in 5 min

**Comment by yenoiwesa** [comment]
Hello there,

There is nothing you or I can do about it. You have had too many unsuccessful attempts targeting the Somfy API (whether from wrong credentials or a Somfy outage).

This is similar to https://github.com/yenoiwesa/homebridge-connexoon/issues/52 so I will close this issue since there is nothing we can do about it but wait. 

TL;DR: You have been temporarily banned by Somfy. Disable the plugin for now and try again in 24h.
