### ISSUE TITLE
Too many attempts with an invalid token, temporarily banned

### ISSUE THREAD

**Issue by HomekitDave** [yenoiwesa/homebridge-connexoon#62]
Seemingly randomly, I’ve received the following error: 

```
Failed to get device list { errorCode: 'RESOURCE ACCESS DENIED'
error: 'Too many attempts with an invalid token, temporarily banned.}
```

I’m not sure if Somfy are messing around, has anyone seen this error before or know how to fix?

PS It’s only just happened so maybe it will fix itself.

**Comment by HomekitDave** [comment]
Having read [Authentication issues #3](https://github.com/yenoiwesa/homebridge-connexoon/issues/3), I tried to login to somfy.co.uk (U.K. based), at first I received an error on the browser `JSON parsing failure at character 1: 'Y' in You exceeded the rate limit“` but I can now login, however It didn’t help unlike #3. I can still login and operate the devices via the Connexoon app.

**Comment by Kositch** [comment]
Same issue... Already happened before, need to wait few days.

**Comment by Kositch** [comment]
But from my experience you must disable the plugin for at least 24 hours and than enable it (it will add shades as new devices to HK sadly).

**Comment by HomekitDave** [comment]
I’ve changed the username the config file, hopefully that will work, I have too many devices to be adding them all again!

**Comment by yenoiwesa** [comment]
😞 Another Somfy down time I assume? This is getting way too frequent.

As last time, sorry guys there is nothing I can do on my end. Everything @Kositch said above ⬆️

**Comment by Kositch** [comment]
Sure, I know - I thought, would be possible - if there is authentication issue with Somfy, we get banned because too frequent login attempts, would it be possible, if login issue happens to immediately stop trying to login let's say for 12 hours so we don't get banned? I assume that Somfy solved the issue in hours, so 12 hours would be enough and we would not need to disable/enable the plugin. I have found out now, that even when it tells me that ban is for 60 hours, it is enough to disable the plugin just for 10 hours (during today's night) re-enabled it now in the morning and everything works. So it seems to me that ban is for constant login attempts based on IP and not the user name - when I changed the username before for 5 days, I had been unable to login afterwards even when the ban should be finished, so I had to stop logging in = disable the plugin and lost all the HK accessories and it solved the problem.

**Comment by yenoiwesa** [comment]
It's possible to implement something like that but it seems very arbitrary. Like, it would be really just a work around for Somfy's poor reliability track record.

**Comment by Kositch** [comment]
Yes, but it would save users time to do again all the device settings and automations in HK after disable/enable the plugin. OR what if there would be possibility to manually stop the plugin from logging in without need to disable it? Let's se some config "Stop logging attempts: True".?

**Comment by HomekitDave** [comment]
Actions I followed to fix:

- Temporarily change the username in config.
- Restart Homebridge. 
- Wait overnight. 
- Renew public IP address (not sure if required). 
- Revert username. 
- Restart Homebridge. 

Thanks all!
