### ISSUE TITLE
Could not initialise platform, will retry in 5 min

### ISSUE THREAD

**Issue by UtterChaos23** [yenoiwesa/homebridge-connexoon#68]
Hi, Awesome plug in by the way.  Only the recent update has prevented my Connexoon blinds from being detected.  Worked seamlessly before.

Error reads: 
```
[11/6/2022, 9:48:09 AM] [My Connexoon Hub] Failed to get device list Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[11/6/2022, 9:48:09 AM] [My Connexoon Hub] Could not initialise platform, will retry in 5 min

Config:

{
            "platform": "Connexoon",
            "name": "My Connexoon Hub",
            "username": "REDACTED",
            "password": "REDACTED",
            "service": "Connexoon"
        },
```
Thanks loads :)

**Comment by yenoiwesa** [comment]
Hello there @UtterChaos23 👋 

In the previous update I just changed a constant for retry interval when the execution queue is full so there is no chance this is causing this error.

Here you are receiving `ECONNRESET` error from node.js. `ECONNRESET` occurs when the server side closes the TCP connection and your request to the server is not fulfilled. This just means in our scenario that the Somfy server closed the connection. It could be due to a network error (with your network or ISP, or Somfy).

Could you try restarting Homebridge and see if the plugin manages to connect?

**Comment by UtterChaos23** [comment]
Hi @yenoiwesa 

Thanks so much for your response.  I had previously tried restarting, re-installing, re-everything! But knowing it was a TCP connection error lead me to look at my NAS (Homebridge) Internet connection.  I turned off the VPN and all worked ok!

I have now rebuild the VPN profile and everything is working perfectly.

Thanks again for your help.

Kind regards , James

**Comment by yenoiwesa** [comment]
Hi @UtterChaos23,

Thanks for the update, and glad that you managed to find the root cause of the issue and were able to fix it!

I'm happy that you enjoy the plug-in!

Cheers,
Matt
